import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day08Test {
    @Test
    fun `given two antennas returns two antinodes`() {
        val antennas = listOf(4 to 3, 5 to 5)

        assertEquals(listOf(3 to 1, 6 to 7), antinodes(antennas, 8,8, false))
    }

    @Test
    fun `given three antennas returns all antinodes extended`() {
        val antennas = listOf(0 to 0, 3 to 1)

        assertEquals(listOf(0 to 0, 3 to 1, 6 to 2, 9 to 3), antinodes(antennas, length = 10, height = 10, true))
    }

    @Test
    fun `given three antennas returns all possible antinodes`() {
        val antennas = listOf(4 to 3, 5 to 5, 8 to 4)

        assertEquals(listOf(3 to 1, 6 to 7, 0 to 2, 2 to 6), antinodes(antennas, 11, 11, false))
    }

    @Test
    fun `parse input`() {
        val input = """
            ..........
            ..........
            ..........
            ....a.....
            ..........
            .....a....
            ..........
            ..........
            ..........
            ..........
        """.trimIndent().split("\n")

        val parsedInput = parseInput(input)


        kotlin.test.assertEquals(mapOf('a' to listOf(4 to 3, 5 to 5)), parsedInput)
    }

    @Test
    fun `Day08 part1`() {
        val input = """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
        """.trimIndent().split("\n")

        val day08 = Day08()

        assertEquals(14, day08.part1(input))
    }

    @Test
    fun `Day08 part2`() {
        val input = """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
        """.trimIndent().split("\n")

        val day08 = Day08()

        assertEquals(34, day08.part2(input))
    }
}